// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype__GoString_ string

type _Ctype_char int8

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})


// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}
//go:cgo_export_dynamic getActiveWindow
//go:linkname _cgoexp_6a4648ea8767_getActiveWindow _cgoexp_6a4648ea8767_getActiveWindow
//go:cgo_export_static _cgoexp_6a4648ea8767_getActiveWindow
func _cgoexp_6a4648ea8767_getActiveWindow(a *struct {
		r0 *_Ctype_char
	}) {
	a.r0 = getActiveWindow()
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic enforce_binding
//go:linkname _cgoexp_6a4648ea8767_enforce_binding _cgoexp_6a4648ea8767_enforce_binding
//go:cgo_export_static _cgoexp_6a4648ea8767_enforce_binding
func _cgoexp_6a4648ea8767_enforce_binding(a *struct {
	}) {
	enforce_binding()
}

//go:cgo_import_static _cgo_6a4648ea8767_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_6a4648ea8767_Cfunc__Cmalloc _cgo_6a4648ea8767_Cfunc__Cmalloc
var __cgofn__cgo_6a4648ea8767_Cfunc__Cmalloc byte
var _cgo_6a4648ea8767_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_6a4648ea8767_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_6a4648ea8767_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
